### 获取请求信息
GET http://localhost:3001/info

### 获取所有联系人
GET http://localhost:3001/api/persons

### 创建单个联系人
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "licc",
  "number": 123456
}

### 更新某个人的信息
PUT http://localhost:3001/api/persons/5ee2f375e5932012c6f014f5a
Content-Type: application/json

{
  "name": "licc",
  "number": 123456789
}


### 获取单个联系人
GET http://localhost:3001/api/persons/5ee2f360e202cb12bef93b08

### 删除单个联系人
DELETE  http://localhost:3001/api/persons/5ee2f360e202cb12bef93b08
